[package]
name = "grimstack"
version = "0.1.1"
authors = ["Saul van der Walt <saul@grimstack.io>"]
edition = "2018"

[dependencies]
# actix-files = { git = "https://github.com/SaulDoesCode/actix-web" }
# actix-web = { git = "https://github.com/SaulDoesCode/actix-web", features = ["rustls"] }
actix-files = "*"
actix-web = { version = "*", features = ["rustls"] }
bincode = "^1.3.1"
borsh = "^0.7.1"
clap = "^2.33.3"
comrak = "^0.8.2"
dashmap = { version="4.0.0-rc6" }
derive_more = "^0.99.9"
flume = "^0.8.4"
futures = "^0.3.5"
lazy_static = "^1.4.0"
itertools = "^0.9.0"
parking_lot = "^0.11.0"
rand = { version = "^0.7.3", features = ["nightly", "simd_support"] }
# rayon = "^1.4.0"
regex = { version = "^1.3.9" }
rust-argon2 = "0.8.2"
rustls = "^0.18.1"
serde = { version = "^1.0.104", features = ["derive"] }
serde_json = "^1.0.57"
# simd-json = "^0.3.20"
sled = { version = "0.34.4", features = ["compression", "rio"] }
slug = "^0.1.4"
sthash = { git = "https://github.com/SaulDoesCode/rust-sthash" }
tera = "^1.5.0"
thiserror = "^1.0.20"
time = { version = "^0.2.20", features = ["serde", "rand"] }
tokio = { version = "^0.2.22", features = ["full"] }
toml = "^0.5.6"
notify = "^5.0.0-pre.3"
walkdir = "^2.3.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"

[profile.dev]
opt-level = 0
debug = true
codegen-units=16
lto = "off"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
codegen-units=1
panic = 'abort'
lto="fat"
